---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

addons:
  apt:
    packages:
      - python-pip

services:
  - utils

before_install:
  - sudo apt-get -qq update

install:
  # Install required dependencies
  - pip install ansible ansible-lint molecule testinfra docker flake8
  # Check Ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Molecule testing
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
